### ISSUE TITLE
ERROR in No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by pkonstan** [PoghosyanHayk/Angular-AI-Chat-Bot#1]
I have followed the instructions by doing the following:

ng new chatbot
cd chatbot
npm install --save angular-ai-chat-bot

At this point I ran **ng serve --open** and it compiled fine and gave me the Angular Heros page

I then edit these three files as follows:

### **app.module.ts**
import` { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import {ChatBot} from 'angular-ai-chat-bot';

@NgModule({
  declarations: [AppComponent, ChatBot],
  imports: [BrowserModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

### **app.component.ts**
import { Component } from '@angular/core';
// 1 - import required classes and interfaces
import { ChatBot } from 'angular-ai-chat-bot';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  // 2 - set [token] attribute to ChatBot object
  template: `<Chat-bot class="chat-window"
                              [token]="accessToken"
                              [msg]="message"
                    >
               <ng-template>
               </ng-template>
             </Chat-bot>`,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'chatbot';
  public accessToken = 'I USED MY ACCESS TOKEN';
  public message: Subject<any> = new Subject();
}

**tsconfig.app.json**

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "include": [
  "../node_modules/angular-ai-chat-bot/*.ts",
   "../node_modules/angular-ai-chat-bot/**/*.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

In your instructions you say, _Voila! That's pretty much it - enjoy 😊_ which gives the impression that I should be able to compile at this point. 

So I then ran ng serve --open

And I get the compile error:
**ERROR in No NgModule metadata found for 'AppModule'.**

Can you provide me some assistance as to why I am getting this error.

Thank you.

Here is all of my version information:
{ chatbot: '0.0.0',
  npm: '6.4.1',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.12.0',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.66',
  zlib: '1.2.11' }

**Comment by kondasMajid** [comment]
you should try adding this to your tsconfig

"files": [
"src/app/app.module.ts"
]

**Comment by pkonstan** [comment]
I have added the above as you suggested and I now get this error:

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-ai-chat-bot/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by kondasMajid** [comment]
probably you should upload your code on Stackblitz or further go through [https://www.npmjs.com/package/angular-ai-chat-bot#wrench-api](url) .
I'm working a simple delivery bot with Angular  i will upload on my GitHub ASAP.

**Comment by pkonstan** [comment]
I ended up coming back to this and found out that what was causing the issue in Angular 6 was the addition of these lines in the tsconfig.app.json file.

"include": [
    "../node_modules/angular-ai-chat-bot/*.ts",
    "../node_modules/angular-ai-chat-bot/**/*.ts"
  ],

Once I removed these, then it again worked.
